roompickr/main_app/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/profile/', views.profile, name='profile'),
    path('accounts/profile/<int:profile_id>/update/', views.update_profile, name='update_profile'),
    path('change-password/', PasswordChangeView.as_view(), name='change_password'),
    path('change-password/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),

    path("search/", views.SearchResultsView.as_view(), name="search_results"),

    path("spaces/", views.space_all, name="space_all"),
    path("spaces/<int:space_id>/detail/", views.space_detail, name="detail"),
    path("spaces/create/", views.SpaceCreate.as_view(), name="spaces_create"),
    path("spaces/<int:pk>/update/", views.SpaceUpdate.as_view(), name="spaces_update"),
    path("spaces/<int:pk>/delete/", views.SpaceDelete.as_view(), name="spaces_delete"),

    path('spaces/<int:space_id>/add_feedback/', views.add_feedback, name='add_feedback'),
    path('spaces/<int:space_id>/edit_feedback/<int:feedback_id>/', views.edit_feedback, name='edit_feedback'),
    path('spaces/<int:space_id>/delete_feedback/<int:feedback_id>/', views.delete_feedback, name='delete_feedback'),

    path('spaces/<int:space_id>/add_image/', views.add_image, name='add_image'),
    path('spaces/<int:space_id>/update_image/<int:image_id>/', views.update_image, name='update_image'),
    path('spaces/<int:space_id>/delete_image/<int:image_id>/', views.delete_image, name='delete_image'),

    path('community/', views.questions, name='questions'),
    path('community/your_questions', views.your_questions, name='your_questions'),
    path('community/questions/<int:user_id>/', views.add_question, name='add_question'),
    path('community/question_detail/<int:question_id>/', views.question_detail, name='question_detail'),
    path('community/question_detail/<int:pk>/update_question/', views.QuestionUpdate.as_view(), name='update_question'),
    path('community/question_detail/<int:pk>/delete_question/', views.QuestionDelete.as_view(), name='delete_question'),
    path('community/answers/<int:user_id>/<int:question_id>/', views.add_answer, name='add_answer'),
    path('community/update_answers/<int:answer_id>/<int:question_id>/', views.update_answer, name='update_answer'),
    path('community/delete_answers/<int:answer_id>/<int:question_id>/', views.delete_answer, name='delete_answer'),

    path('spaces/<int:pk>/booking/', views.start_booking.as_view(), name='start_booking' ),
    path('space/<int:pk>/booking_detail/', views.BookingDetail.as_view(), name='booking_detail'),
    path("spaces/booking_history", views.booking_history, name="booking_history"),
    path('spaces/delete_booking/<int:pk>/', views.DeleteBooking.as_view(), name='delete_booking'),
    path('spaces/invoice_booking/<int:book_id>/', views.invoice_booking, name='invoice_booking'),

]

roompickr/roompickr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

roompickr/main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator



TYPES=(
    ('O', 'Office'),
    ('H', 'Hall'),
    ('M', 'Meeting Room'),
)


GENDERS=(
    ('F', 'Female'),
    ('M', 'Male')
)

# Create your models here.

class Profile(models.Model):
    user= models.OneToOneField(User, on_delete=models.CASCADE)

    full_name = models.CharField(max_length=100)
    email= models.EmailField(max_length=245)
    avatar = models.ImageField(upload_to='main_app/static/profile/', default='')
    gender= models.CharField(max_length=1, choices=GENDERS, default=GENDERS[0][0])

    def __str__(self):
        return self.name


class Space(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    capacity= models.IntegerField(default=1, validators=[MinValueValidator(1)])
    description = models.TextField()
    thumbnail = models.ImageField(upload_to='main_app/static/thumbnails/', default='')
    type= models.CharField(max_length=1, choices=TYPES, default=TYPES[0][0])
    price_per_hour= models.IntegerField(default=1, validators=[MinValueValidator(1)])
    user= models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("detail", kwargs={"space_id" : self.id})

class Image(models.Model):
    image_space = models.ImageField(upload_to='main_app/static/uploads/', default='')
    caption = models.TextField(max_length=150)
    space=models.ForeignKey(Space, on_delete=models.CASCADE)

    def __str__(self):
        return self.space.name


class Feedback(models.Model):
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    comment= models.TextField(max_length=234)
    space=models.ForeignKey(Space, on_delete=models.CASCADE)
    user= models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.space.name}, {self.user.username}'


class Booking(models.Model):
    start=models.DateTimeField(null=True)
    end=models.DateTimeField(null=True)
    total_price=models.IntegerField()
    space=models.ForeignKey(Space, on_delete=models.CASCADE)
    user= models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'booking {self.space.name} for {self.user.username}'

    def get_absolute_url(self):
        return reverse("booking_detail", kwargs={"pk": self.id})

    def total_price_calculate(self):
        total = self.end - self.start
        hours = total.total_seconds() / 3600
        self.total_price = int(hours * self.space.price_per_hour)
        return self.total_price

    def clean(self):
        if self.end <= self.start:
            return "End date must be after Start Date!"

        if self.start and self.end:
            booking_validation_stop_overlapping =Booking.objects.filter(start__lte=self.end, end__gte=self.start, space=self.space_id).exclude(id=self.id)
            if booking_validation_stop_overlapping:
                return "Times overlap with existing record!"



class Question(models.Model):
    created_at=models.DateTimeField(auto_now_add=True)
    title=models.CharField(max_length=150)
    content= models.TextField(max_length=500)
    user= models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.title} from {self.user.username}'

    def get_absolute_url(self):
        return reverse("question_detail", kwargs={"question_id" : self.id})

class Answer(models.Model):
    created_at=models.DateTimeField(auto_now_add=True)
    answer= models.TextField(max_length=500)
    question= models.ForeignKey(Question, on_delete=models.CASCADE)
    user= models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'answer of {self.question} from {self.user.username}'

roompickr/main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ProfileForm, UserForm, FeedbackForm, ImageForm, QuestionForm, AnswerForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Profile, Space, Image, Feedback, Booking, Question, Answer

from django.utils import timezone


from django_xhtml2pdf.utils import generate_pdf

from django.core.mail import EmailMessage
from django.template.loader import render_to_string

import qrcode
from io import BytesIO
import base64


# Create your views here.
@login_required
def home(request):
    return render(request, "home.html")


@login_required
def about(request):
    return render(request, "about.html")


@login_required
def contact_us(request):
    return render(request, "contact.html")

# @login_required
# def rooms_index(request):
#     return render (request, 'rooms/index.html')


def signup(request):
    error_message = ""
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("profile")
        else:
            error_message = "Invalid Sign Up, Try again later..."
    form = UserCreationForm()
    context = {"form": form, "error_message": error_message}
    return render(request, "registration/signup.html", context)

@login_required
def profile(request):
    profiles = Profile.objects.filter(user=request.user)
    return render(request, "users/profile.html", {"profiles": profiles})


@login_required
def update_profile(request, profile_id):
    profile = Profile.objects.get(id=profile_id)
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=profile)

        if user_form.is_valid() and profile_form.is_valid():
            profile_form.save()
            user_form.save()
            return redirect("/accounts/profile/")
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=profile)

    return render(
        request,
        "users/update_profile.html",
        {"user_form": user_form, "profile_form": profile_form},
    )


@login_required
def space_all(request):
    spaces = Space.objects.all()
    return render(request, "spaces/all_space.html", {"spaces": spaces})


@login_required
def space_detail(request, space_id):
    space = Space.objects.get(id=space_id)
    feedback_form = FeedbackForm()
    image_form = ImageForm()
    return render(
        request,
        "spaces/detail.html",
        {"space": space, "feedback_form": feedback_form, "image_form": image_form},
    )


class SpaceCreate(LoginRequiredMixin, CreateView):
    model = Space
    fields = ["name", "address", "capacity", "type", "price_per_hour", "description", "thumbnail"]

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class SpaceUpdate(LoginRequiredMixin, UpdateView):
    model = Space
    fields = ["name", "address", "capacity", "type", "price_per_hour", "description", "thumbnail"]


class SpaceDelete(LoginRequiredMixin, DeleteView):
    model = Space
    success_url = "/spaces/"


@login_required
def add_feedback(request, space_id):
    form = FeedbackForm(request.POST)
    if form.is_valid():
        new_feedback = form.save(commit=False)
        new_feedback.space_id = space_id
        new_feedback.user = request.user
        new_feedback.save()
    return redirect('detail', space_id)

#edit/update
@login_required
def edit_feedback(request, space_id, feedback_id):
    review = Feedback.objects.get(id=feedback_id)
    form = FeedbackForm()
    if request.method == "POST":
        form= FeedbackForm(request.POST, instance=review)
    if form.is_valid():
        new_feedback = form.save(commit=False)
        new_feedback.space_id = space_id
        new_feedback.save()
    return redirect('detail', space_id)



def delete_feedback(request, space_id, feedback_id):
    feedback = Feedback.objects.get(id=feedback_id)
    if feedback:
        feedback.delete()
    return redirect("detail", space_id)

@login_required
def add_image(request, space_id):
    form = ImageForm(request.POST, request.FILES)
    if form.is_valid():
        new_image = form.save(commit=False)
        new_image.space_id = space_id
        new_image.save()
    return redirect("detail", space_id)


@login_required
def update_image(request, space_id, image_id):
    image = Image.objects.get(id=image_id)
    image_form = ImageForm()
    if request.method == "POST":
        form = ImageForm(request.POST, request.FILES, instance=image)
        if form.is_valid():
            image_update = form.save(commit=False)
            image_update.space_id = space_id
            image_update.save()
        return redirect("detail", space_id)
    else:
        form = ImageForm(instance=image)

    return render(request, 'spaces/detail.html', {'image_form': image_form, 'space_id': space_id})

@login_required
def delete_image(request, space_id, image_id):
    image = Image.objects.get(id=image_id)
    if image:
        image.delete()
    return redirect("detail", space_id)

@login_required
def your_questions(request):
    questions = Question.objects.filter(user=request.user)
    question_form = QuestionForm()
    return render(request, "community/your_question.html", {"questions": questions, "question_form": question_form})

@login_required
def questions(request):
    questions = Question.objects.all()
    question_form = QuestionForm()
    return render(request, "community/question.html", {"questions": questions, "question_form": question_form})

@login_required
def add_question(request, user_id):
    form = QuestionForm(request.POST)
    if form.is_valid():
        new_question = form.save(commit=False)
        new_question.user_id = user_id
        new_question.save()
    return redirect("questions")

@login_required
def question_detail(request, question_id):
    question = Question.objects.get(id=question_id)
    answer_form = AnswerForm()
    return render(request, "community/detail_question.html", {"question": question, "question_id": question_id, "answer_form": answer_form})

class QuestionUpdate(LoginRequiredMixin, UpdateView):
    model = Question
    fields = ['title', 'content']

class QuestionDelete(LoginRequiredMixin, DeleteView):
    model = Question
    success_url = "/community/"

@login_required
def add_answer(request, user_id, question_id):
    form = AnswerForm(request.POST)
    if form.is_valid():
        new_answer = form.save(commit=False)
        new_answer.question_id = question_id
        new_answer.user_id = user_id
        new_answer.save()
    return redirect("question_detail", question_id)

@login_required
def update_answer(request, answer_id, question_id):
    answer = Answer.objects.get(id=answer_id)
    answer_form = AnswerForm()
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer_update = form.save(commit=False)
            answer_update.question_id = question_id
            answer_update.save()
        return redirect("question_detail", question_id)
    else:
        form = AnswerForm(instance=answer)

    return render(request, 'community/detail_question.html', {'answer_form': answer_form, 'question_id': question_id})

@login_required
def delete_answer(request, answer_id, question_id):
    answer = Answer.objects.get(id=answer_id)
    if answer:
        answer.delete()
    return redirect("question_detail", question_id)

class start_booking(LoginRequiredMixin, CreateView):
    model = Booking
    fields = ['start', 'end']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        space = Space.objects.get(id=self.kwargs["pk"])
        context["price_per_hour"] = space.price_per_hour
        return context

    def form_valid(self, form):
        form.instance.space_id = self.kwargs["pk"]
        form.instance.user = self.request.user
        booking = form.save(commit=False)

        # This part form AI
        validation_msg = booking.clean()
        if validation_msg:
            form.add_error(None, validation_msg)
            return self.form_invalid(form)
        # End part AI

        booking.total_price_calculate()
        booking.save()

        def send_welcome_email():
            qr_data = (
                f"Booking ID: {booking.id}\n"
                f"User Name: {self.request.user.profile.full_name}\n"
                f"Email: {self.request.user.profile.email}\n"
                f"Start: {booking.start}\n"
                f"End: {booking.end}\n"
                f"Total Price: {booking.total_price}"
            )

            qr = qrcode.QRCode(
                version=1,
                error_correction=qrcode.constants.ERROR_CORRECT_L,
                box_size=10,
                border=4,
            )
            qr.add_data(qr_data)
            qr.make(fit=True)
            img = qr.make_image(fill_color="black", back_color="white")
            buffered = BytesIO()
            img.save(buffered, format="PNG")

            subject = 'Thank You for Your Booking'
            html_message = render_to_string('emails/booking_email.html', {
                'booking': booking,
                'user': self.request.user,
                'qr_code_image': 'cid:qr_code.png',
            })

            email = EmailMessage(
                subject=subject,
                body=html_message,
                to=[self.request.user.profile.email],

roompickr/main_app/templates/main_app/booking_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="delete-box-booking">
<h1 class="delete-booking-title">Delete your Booking</h1>



<div class="warning">
  <strong>Warning:</strong> You will Delete your Booking permanently
</div>

<h4 class="delete-booking-subtitle">
  Are you sure you want to delete your <strong>{{ booking.space.name }}</strong> Booking?
</h4>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn delete-btn"/>
    <a href="{% url 'booking_detail' booking.id %}" class="btn cancel-btn">Cancel</a>
</form>
</div>
{% endblock %}

roompickr/main_app/templates/main_app/booking_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="detail-booking-card">
  <h2>Booking Details for <span>{{ booking.space.name }}</span></h2>

  <div class="detail-row">
    <span class="label">Start At:</span>
    <span class="value">{{ booking.start }}</span>
  </div>

  <div class="detail-row">
    <span class="label">Ends At:</span>
    <span class="value">{{ booking.end }}</span>
  </div>

  <div class="detail-row">
    <span class="label">Total Price:</span>
    <span class="value">{{ booking.total_price }} BHD</span>
  </div>

  <div class="booking-actions">
    <a href="{% url 'invoice_booking' booking.id %}" class="booking-btn export">Export Invoice</a>
    <a href="{% url 'delete_booking' booking.id %}" class="booking-btn delete">Delete Booking</a>
  </div>
</div>

{% endblock %}

roompickr/main_app/templates/main_app/booking_form.html
{% extends 'base.html' %}
{% block content %}

<h1 class="booking-title">Book Your Space</h1>

<div class="booking-wrapper">
  <form action="" method="post" class="booking-form">
    {% if form.non_field_errors %}
      <div class="booking-error">
        <span class="error-symbol">&#x2716; </span> {{ form.non_field_errors }}
      </div>
    {% endif %}
    {% csrf_token %}

    <div class="form-group">
      <label for="id_start" class="form-label">Start Time</label>
      <input id="id_start" name="start" type="datetime-local" class="form-input datetime-input" />
    </div>

    <div class="form-group">
      <label for="id_end" class="form-label">End Time</label>
      <input id="id_end" name="end" type="datetime-local" class="form-input datetime-input" />
    </div>

    <p class="price-info">Price per hour: <span id="price" class="price-value">{{price_per_hour}}</span> BHD</p>

    <button class="btn btn-check-time" type="button">Check Total Price</button>

    <p class="total-price-info">Total Price: <span id="total_price" class="total-price-value">0</span> BHD</p>

    <p class="booking-note">
      <strong>&#9888; Warning!</strong> You will receive an email with a QR code. Please show this code to the space owner to confirm your identity.
    </p>


    <input type="submit" value="Book Your Space" class="btn btn-submit" />
  </form>
</div>

<script>
  const pricePerHour = document.querySelector("#price")
  const totalPrice = document.querySelector("#total_price")
  const timeBtn = document.querySelector(".btn-check-time")
  let today = new Date().toISOString().slice(0, 16)
  document.querySelector("#id_start").min = today
  document.querySelector("#id_end").min = today

  const pricingCalculation = () => {
    let startTime = document.querySelector("#id_start").value
    let endTime = document.querySelector("#id_end").value
    if (!startTime || !endTime) return
    let result = (new Date(endTime) - new Date(startTime)) / (1000 * 3600)

    let price = Number(pricePerHour.innerText)
    let total = result * price
    totalPrice.innerText = total.toFixed(2)
  }

  timeBtn.addEventListener("click", pricingCalculation)
</script>

{% endblock %}

roompickr/main_app/templates/main_app/invoice.html
<style>
  /* ===========================
   Global Page Styling
   =========================== */
.invoice-body {
    font-family: "Helvetica", sans-serif;
    font-size: 13px;
    color: #333;
}

/* ===========================
   Header
   =========================== */
.invoice-header {
    text-align: center;
}

.invoice-logo {
    width: 80px;
    margin-bottom: 10px;
}

.invoice-title {
    font-size: 26px;
    font-weight: bold;
}

.invoice-divider {
    border: 0;
}


/* ===========================
   Booking Sections
   =========================== */
.booking-section {
    padding: 18px 20px;
}

.booking-title {
    font-size: 18px;
    font-weight: bold;
}

.booking-subtitle {
    font-size: 15px;
    color: #555;
    margin-top: -20px;
}


/* ===========================
   Booking Table
   =========================== */
.booking-table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 12px;
}

.booking-table th {
    background: #f2f2f2;
    padding: 10px;
    font-size: 13px;
    border: 1px solid #ccc;
}

.booking-table td {
    padding: 10px;
    border: 1px solid #ccc;
    font-size: 13px;
}


/* ===========================
   No Booking Section
   =========================== */
.no-booking {
    text-align: center;
    font-size: 14px;
    padding: 20px;
    border: 1px dashed #aaa;
}


/* ===========================
   Terms & Conditions
   =========================== */
.invoice-terms {
    font-size: 13px;
    margin-top: 10px;
    margin-bottom: 15px;
}

.invoice-terms h4 {
    font-size: 16px;
    padding-top: 25px;

}

.invoice-terms ul {
    padding-left: 18px;
}


/* ===========================
   Footer
   =========================== */
.invoice-footer {
    text-align: left;
}

.invoice-footer h4 {
    margin-bottom: 5px;
    font-size: 15px;
}

.footer-note {
    padding-top: 40px;
    font-style: italic;
    font-size: 12px;
    color: #666;
}

</style>


<body class="invoice-body">
  <!-- Header with Logo -->
  <div class="invoice-header">
    <img src="https://img.sanishtech.com/u/7e837eb148f5c3ca3057c7410754a215.png" class="invoice-logo" alt="RoomPickr Logo"/>
    <h1 class="invoice-title">Invoice</h1>
    <div class="invoice-meta">
      <p>Date: {% now "d-M-Y" %}</p>
      <p>Time: {% now "h:i:s" %}</p>
      <p>Payment Method: CASH</p>
    </div>
    <hr class="invoice-divider"/>
  </div>

  <!-- Booking Details -->
  {% if booking %}
    <div class="invoice-content">
      {% for book in booking %}
      <div class="booking-section">
        <h2 class="booking-title">Booking #{{ book.id }}</h2>
        <h3 class="booking-subtitle">Space: {{ book.space.name }}</h3>

        <table class="booking-table">
          <thead>
            <tr>
              <th>Start At</th>
              <th>Ends At</th>
              <th>Total Price (BHD)</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{{ book.start }}</td>
              <td>{{ book.end }}</td>
              <td>{{ book.total_price }}</td>
            </tr>
          </tbody>
        </table>
      </div>
      {% endfor %}
    </div>
  {% else %}
    <div class="no-booking">
      <p>No bookings found for this invoice.</p>
    </div>
  {% endif %}

  <!-- Terms & Conditions -->
  <div class="invoice-terms">
  <h4>Terms & Conditions</h4>
  <ul>
    <li>Payment must be made in person at the time of arrival.</li>
    <li>Guests must arrive no later than 15 minutes after the scheduled booking time. Late arrivals will result in automatic cancellation.</li>
    <li>The email containing the QR code must not be deleted, as it is required for check-in verification.</li>
  </ul>
</div>


  <!-- Footer -->
  <div class="invoice-footer">
    <h4>From:</h4>
    <p>RoomPickr</p>
    <p>Email: roompickr@gmail.com</p>
    <p>Phone: +973-32653198</p>
    <p class="footer-note">Booking Spaces for Everyone</p>
  </div>
</body>

roompickr/main_app/templates/main_app/question_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="community-page">
<div class="delete-box">


<div class="warning">
  <strong>Warning:</strong> Deleting this question will also permanently remove all associated answer
</div>




  <h1>Delete Question</h1>
  <h4>
    Are you sure you want to delete
    <strong>{{ question.title }}</strong>?
  </h4>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn delete-btn"/>
    <a href="{% url 'question_detail' question.id %}" class="btn cancel-btn">Cancel</a>
  </form>
</div>
</div>
{% endblock %}

roompickr/main_app/templates/main_app/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="community-page">
<div class="edit-page-box">
    <h1>Edit <br>
      <span>{{question.title}}</span></h1>
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_p }}
    </table>
    <input type="submit" value="Submit!">
  </form>
</div>
</div>
{% endblock %}

roompickr/main_app/templates/main_app/space_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="delete-box-space">
  <h1>Delete Space</h1>
  <h4>Are you sure you want to delete <strong>{{ space.name }}</strong>?</h4>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn delete-btn"/>
    <a href="{% url 'detail' space.id %}" class="btn cancel-btn">Cancel</a>
  </form>
</div>
{% endblock %}

roompickr/main_app/templates/main_app/space_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>Space Details</h1>
<div>
  <div>
    <div>
        <h4><span style="font-size: 28px;">{{ space.name }}</span></h4>
        <h4><strong>Address:</strong> {{ space.address }}</h4>
        <h4><strong>Capacity:</strong> {{space.capacity}}</h4>
        <h4><strong>Type:</strong> {{space.get_type_display}}</h4>
        <h4><strong>Price Per Hour:</strong> {{space.price_per_hour}}</h4>
      <div>
        <a href="{% url 'spaces_update' space.id %}">Edit</a>
        <a href="{% url 'spaces_delete' space.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
<div>
 <form action="{% url 'add_feedback' space.id %}" method="post">
    {% csrf_token %}
    {{ feedback_form.as_p }}
    <input type="submit" value="Add Feedback" class="btn" />
  </form>
</div>
<div>
  {% if space.feedback_set.count  %}
  {% for feedback in space.feedback_set.all %}
  <span>{{feedback.created_at}}</span>
  <h4>{{feedback.comment}}</h4>
  {% endfor %}
  {% endif %}
</div>

{% endblock %}

roompickr/main_app/templates/main_app/space_form.html
{% extends 'base.html' %}
{% block content %}
<div class="space-add-container">
  {% if space %}
    <h1 class="space-add-title">Edit <span>{{space.name}}</span></h1>
  {% else %}
    <h1 class="space-add-title">Add Space</h1>
  {% endif %}
  <form class="space-add-form" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
      {{ form.as_p }}
    <input class="space-add-submit" type="submit" value="Submit!">
  </form>
</div>
{% endblock %}

roompickr/main_app/templates/main_app/space_list.html
{% extends 'base.html' %}
{% block content %}
<img src="/static/images/image3.png" alt="" class="image-banner">
<ul>
  {% for space in object_list %}
  <div class="sapce-card">
    <div class="sapce-card__image">
    {% load static %}
    <img src={% static space.thumbnail|cut:'main_app/static/' %}
  alt="this for {{space.name}}"/>
  </div>

  <div class="sapce-card__content">
  <div class="sapce-title-row">
    <h1 class="sapce-title">{{ space.name }}</h1>
    <span class="sapce-tag">{{ space.get_type_display }}</span>
  </div>

  <ul class="sapce-info">
    <li><i class="fi fi-ss-person-simple space-icon"></i>{{ space.capacity }}</li>
    <li><i class="fi fi-ss-marker space-icon"></i> {{ space.address }}</li>
    <li><i class="fi fi-ss-usd-circle space-icon"></i> {{ space.price_per_hour }} BHD</li>
  </ul>

  <div class="sapce-actions">
    <a class="sapce-btn" href="{% url 'detail' space.id %}">More Details</a>
  </div>
</div>

</div>
  {% endfor %}
</ul>
{% endblock %}