roompickr/main_app/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/profile/', views.profile, name='profile'),
    path('accounts/profile/<int:profile_id>/update/', views.update_profile, name='update_profile'),
    path('change-password/', PasswordChangeView.as_view(), name='change_password'),
    path('change-password/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),

    path("search/", views.SearchResultsView.as_view(), name="search_results"),

    path("spaces/", views.space_all, name="space_all"),
    path("spaces/<int:space_id>/detail/", views.space_detail, name="detail"),
    path("spaces/create/", views.SpaceCreate.as_view(), name="spaces_create"),
    path("spaces/<int:pk>/update/", views.SpaceUpdate.as_view(), name="spaces_update"),
    path("spaces/<int:pk>/delete/", views.SpaceDelete.as_view(), name="spaces_delete"),

    path('spaces/<int:space_id>/add_feedback/', views.add_feedback, name='add_feedback'),
    path('spaces/<int:space_id>/edit_feedback/<int:feedback_id>/', views.edit_feedback, name='edit_feedback'),
    path('spaces/<int:space_id>/delete_feedback/<int:feedback_id>/', views.delete_feedback, name='delete_feedback'),

    path('spaces/<int:space_id>/add_image/', views.add_image, name='add_image'),
    path('spaces/<int:space_id>/update_image/<int:image_id>/', views.update_image, name='update_image'),
    path('spaces/<int:space_id>/delete_image/<int:image_id>/', views.delete_image, name='delete_image'),

    path('community/', views.questions, name='questions'),
    path('community/your_questions', views.your_questions, name='your_questions'),
    path('community/questions/<int:user_id>/', views.add_question, name='add_question'),
    path('community/question_detail/<int:question_id>/', views.question_detail, name='question_detail'),
    path('community/question_detail/<int:pk>/update_question/', views.QuestionUpdate.as_view(), name='update_question'),
    path('community/question_detail/<int:pk>/delete_question/', views.QuestionDelete.as_view(), name='delete_question'),
    path('community/answers/<int:user_id>/<int:question_id>/', views.add_answer, name='add_answer'),
    path('community/update_answers/<int:answer_id>/<int:question_id>/', views.update_answer, name='update_answer'),
    path('community/delete_answers/<int:answer_id>/<int:question_id>/', views.delete_answer, name='delete_answer'),

    path('spaces/<int:pk>/booking/', views.start_booking.as_view(), name='start_booking' ),
    path('space/<int:pk>/booking_detail/', views.BookingDetail.as_view(), name='booking_detail'),
    path("spaces/booking_history", views.booking_history, name="booking_history"),
    path('spaces/delete_booking/<int:pk>/', views.DeleteBooking.as_view(), name='delete_booking'),
    path('spaces/invoice_booking/<int:book_id>/', views.invoice_booking, name='invoice_booking'),

]

roompickr/roompickr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

roompickr/main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator



TYPES=(
    ('O', 'Office'),
    ('H', 'Hall'),
    ('M', 'Meeting Room'),
)


GENDERS=(
    ('F', 'Female'),
    ('M', 'Male')
)

# Create your models here.

class Profile(models.Model):
    user= models.OneToOneField(User, on_delete=models.CASCADE)

    full_name = models.CharField(max_length=100)
    email= models.EmailField(max_length=245)
    avatar = models.ImageField(upload_to='main_app/static/profile/', default='')
    gender= models.CharField(max_length=1, choices=GENDERS, default=GENDERS[0][0])

    def __str__(self):
        return self.name


class Space(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    capacity= models.IntegerField(default=1, validators=[MinValueValidator(1)])
    description = models.TextField()
    thumbnail = models.ImageField(upload_to='main_app/static/thumbnails/', default='')
    type= models.CharField(max_length=1, choices=TYPES, default=TYPES[0][0])
    price_per_hour= models.IntegerField(default=1, validators=[MinValueValidator(1)])
    user= models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("detail", kwargs={"space_id" : self.id})

class Image(models.Model):
    image_space = models.ImageField(upload_to='main_app/static/uploads/', default='')
    caption = models.TextField(max_length=150)
    space=models.ForeignKey(Space, on_delete=models.CASCADE)

    def __str__(self):
        return self.space.name


class Feedback(models.Model):
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    comment= models.TextField(max_length=234)
    space=models.ForeignKey(Space, on_delete=models.CASCADE)
    user= models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.space.name}, {self.user.username}'


class Booking(models.Model):
    start=models.DateTimeField(null=True)
    end=models.DateTimeField(null=True)
    total_price=models.IntegerField()
    space=models.ForeignKey(Space, on_delete=models.CASCADE)
    user= models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'booking {self.space.name} for {self.user.username}'

    def get_absolute_url(self):
        return reverse("booking_detail", kwargs={"pk": self.id})

    def total_price_calculate(self):
        total = self.end - self.start
        hours = total.total_seconds() / 3600
        self.total_price = int(hours * self.space.price_per_hour)
        return self.total_price

    def clean(self):
        if self.end <= self.start:
            return "End date must be after Start Date!"

        if self.start and self.end:
            booking_validation_stop_overlapping =Booking.objects.filter(start__lte=self.end, end__gte=self.start, space=self.space_id).exclude(id=self.id)
            if booking_validation_stop_overlapping:
                return "Times overlap with existing record!"



class Question(models.Model):
    created_at=models.DateTimeField(auto_now_add=True)
    title=models.CharField(max_length=150)
    content= models.TextField(max_length=500)
    user= models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.title} from {self.user.username}'

    def get_absolute_url(self):
        return reverse("question_detail", kwargs={"question_id" : self.id})

class Answer(models.Model):
    created_at=models.DateTimeField(auto_now_add=True)
    answer= models.TextField(max_length=500)
    question= models.ForeignKey(Question, on_delete=models.CASCADE)
    user= models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'answer of {self.question} from {self.user.username}'

roompickr/main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ProfileForm, UserForm, FeedbackForm, ImageForm, QuestionForm, AnswerForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Profile, Space, Image, Feedback, Booking, Question, Answer

from django.utils import timezone


from django_xhtml2pdf.utils import generate_pdf

from django.core.mail import EmailMessage
from django.template.loader import render_to_string

import qrcode
from io import BytesIO
import base64


# Create your views here.
@login_required
def home(request):
    return render(request, "home.html")


@login_required
def about(request):
    return render(request, "about.html")


@login_required
def contact_us(request):
    return render(request, "contact.html")

# @login_required
# def rooms_index(request):
#     return render (request, 'rooms/index.html')


def signup(request):
    error_message = ""
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("profile")
        else:
            error_message = "Invalid Sign Up, Try again later..."
    form = UserCreationForm()
    context = {"form": form, "error_message": error_message}
    return render(request, "registration/signup.html", context)

@login_required
def profile(request):
    profiles = Profile.objects.filter(user=request.user)
    return render(request, "users/profile.html", {"profiles": profiles})


@login_required
def update_profile(request, profile_id):
    profile = Profile.objects.get(id=profile_id)
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=profile)

        if user_form.is_valid() and profile_form.is_valid():
            profile_form.save()
            user_form.save()
            return redirect("/accounts/profile/")
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=profile)

    return render(
        request,
        "users/update_profile.html",
        {"user_form": user_form, "profile_form": profile_form},
    )


@login_required
def space_all(request):
    spaces = Space.objects.all()
    return render(request, "spaces/all_space.html", {"spaces": spaces})


@login_required
def space_detail(request, space_id):
    space = Space.objects.get(id=space_id)
    feedback_form = FeedbackForm()
    image_form = ImageForm()
    return render(
        request,
        "spaces/detail.html",
        {"space": space, "feedback_form": feedback_form, "image_form": image_form},
    )


class SpaceCreate(LoginRequiredMixin, CreateView):
    model = Space
    fields = ["name", "address", "capacity", "type", "price_per_hour", "description", "thumbnail"]

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class SpaceUpdate(LoginRequiredMixin, UpdateView):
    model = Space
    fields = ["name", "address", "capacity", "type", "price_per_hour", "description", "thumbnail"]


class SpaceDelete(LoginRequiredMixin, DeleteView):
    model = Space
    success_url = "/spaces/"


@login_required
def add_feedback(request, space_id):
    form = FeedbackForm(request.POST)
    if form.is_valid():
        new_feedback = form.save(commit=False)
        new_feedback.space_id = space_id
        new_feedback.user = request.user
        new_feedback.save()
    return redirect('detail', space_id)

#edit/update
@login_required
def edit_feedback(request, space_id, feedback_id):
    review = Feedback.objects.get(id=feedback_id)
    form = FeedbackForm()
    if request.method == "POST":
        form= FeedbackForm(request.POST, instance=review)
    if form.is_valid():
        new_feedback = form.save(commit=False)
        new_feedback.space_id = space_id
        new_feedback.save()
    return redirect('detail', space_id)



def delete_feedback(request, space_id, feedback_id):
    feedback = Feedback.objects.get(id=feedback_id)
    if feedback:
        feedback.delete()
    return redirect("detail", space_id)

@login_required
def add_image(request, space_id):
    form = ImageForm(request.POST, request.FILES)
    if form.is_valid():
        new_image = form.save(commit=False)
        new_image.space_id = space_id
        new_image.save()
    return redirect("detail", space_id)


@login_required
def update_image(request, space_id, image_id):
    image = Image.objects.get(id=image_id)
    image_form = ImageForm()
    if request.method == "POST":
        form = ImageForm(request.POST, request.FILES, instance=image)
        if form.is_valid():
            image_update = form.save(commit=False)
            image_update.space_id = space_id
            image_update.save()
        return redirect("detail", space_id)
    else:
        form = ImageForm(instance=image)

    return render(request, 'spaces/detail.html', {'image_form': image_form, 'space_id': space_id})

@login_required
def delete_image(request, space_id, image_id):
    image = Image.objects.get(id=image_id)
    if image:
        image.delete()
    return redirect("detail", space_id)

@login_required
def your_questions(request):
    questions = Question.objects.filter(user=request.user)
    question_form = QuestionForm()
    return render(request, "community/your_question.html", {"questions": questions, "question_form": question_form})

@login_required
def questions(request):
    questions = Question.objects.all()
    question_form = QuestionForm()
    return render(request, "community/question.html", {"questions": questions, "question_form": question_form})

@login_required
def add_question(request, user_id):
    form = QuestionForm(request.POST)
    if form.is_valid():
        new_question = form.save(commit=False)
        new_question.user_id = user_id
        new_question.save()
    return redirect("questions")

@login_required
def question_detail(request, question_id):
    question = Question.objects.get(id=question_id)
    answer_form = AnswerForm()
    return render(request, "community/detail_question.html", {"question": question, "question_id": question_id, "answer_form": answer_form})

class QuestionUpdate(LoginRequiredMixin, UpdateView):
    model = Question
    fields = ['title', 'content']

class QuestionDelete(LoginRequiredMixin, DeleteView):
    model = Question
    success_url = "/community/"

@login_required
def add_answer(request, user_id, question_id):
    form = AnswerForm(request.POST)
    if form.is_valid():
        new_answer = form.save(commit=False)
        new_answer.question_id = question_id
        new_answer.user_id = user_id
        new_answer.save()
    return redirect("question_detail", question_id)

@login_required
def update_answer(request, answer_id, question_id):
    answer = Answer.objects.get(id=answer_id)
    answer_form = AnswerForm()
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer_update = form.save(commit=False)
            answer_update.question_id = question_id
            answer_update.save()
        return redirect("question_detail", question_id)
    else:
        form = AnswerForm(instance=answer)

    return render(request, 'community/detail_question.html', {'answer_form': answer_form, 'question_id': question_id})

@login_required
def delete_answer(request, answer_id, question_id):
    answer = Answer.objects.get(id=answer_id)
    if answer:
        answer.delete()
    return redirect("question_detail", question_id)

class start_booking(LoginRequiredMixin, CreateView):
    model = Booking
    fields = ['start', 'end']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        space = Space.objects.get(id=self.kwargs["pk"])
        context["price_per_hour"] = space.price_per_hour
        return context

    def form_valid(self, form):
        form.instance.space_id = self.kwargs["pk"]
        form.instance.user = self.request.user
        booking = form.save(commit=False)

        # This part form AI
        validation_msg = booking.clean()
        if validation_msg:
            form.add_error(None, validation_msg)
            return self.form_invalid(form)
        # End part AI

        booking.total_price_calculate()
        booking.save()

        def send_welcome_email():
            qr_data = (
                f"Booking ID: {booking.id}\n"
                f"User Name: {self.request.user.profile.full_name}\n"
                f"Email: {self.request.user.profile.email}\n"
                f"Start: {booking.start}\n"
                f"End: {booking.end}\n"
                f"Total Price: {booking.total_price}"
            )

            qr = qrcode.QRCode(
                version=1,
                error_correction=qrcode.constants.ERROR_CORRECT_L,
                box_size=10,
                border=4,
            )
            qr.add_data(qr_data)
            qr.make(fit=True)
            img = qr.make_image(fill_color="black", back_color="white")
            buffered = BytesIO()
            img.save(buffered, format="PNG")

            subject = 'Thank You for Your Booking'
            html_message = render_to_string('emails/booking_email.html', {
                'booking': booking,
                'user': self.request.user,
                'qr_code_image': 'cid:qr_code.png',
            })

            email = EmailMessage(
                subject=subject,
                body=html_message,
                to=[self.request.user.profile.email],

roompickr/main_app/templates/spaces/all_space.html
{% extends 'base.html' %}
{% block content %}
<img src="/static/images/image1.png" alt="" class="image-banner">
<div class="top-controls">
    <div class="filter-container">
        <form action="{% url 'search_results' %}" method="get" class="filter-form">
          <div class="filter-inline">
            <div class="filter-dropdown">
              <div class="filter-dropdown-toggle" id="dropdown-toggle">Office</div>
              <ul class="filter-dropdown-menu" id="dropdown-menu">
                <li data-value="O">Office</li>
                <li data-value="H">Hall</li>
                <li data-value="M">Meeting Room</li>
              </ul>
            </div>

            <input type="hidden" name="type" id="selected-type" value="O" />
            <button type="submit" class="filter-btn">Filter</button>
          </div>
        </form>
    </div>

    {% if user.is_superuser %}
    <div class="spaces-admin-links">
      <a href="{% url 'spaces_create' %}">Add a Space</a>
    </div>
    {% endif %}
</div>


{% for space in spaces %}
<div class="sapce-card">
    <div class="sapce-card__image">
    {% load static %}
    <img src={% static space.thumbnail|cut:'main_app/static/' %}
  alt="this for {{space.name}}"/>
  </div>

  <div class="sapce-card__content">
  <div class="sapce-title-row">
    <h1 class="sapce-title">{{ space.name }}</h1>
    <span class="sapce-tag">{{ space.get_type_display }}</span>
  </div>

  <ul class="sapce-info">
    <li><i class="fi fi-ss-person-simple space-icon"></i>{{ space.capacity }}</li>
    <li><i class="fi fi-ss-marker space-icon"></i> {{ space.address }}</li>
    <li><i class="fi fi-ss-usd-circle space-icon"></i> {{ space.price_per_hour }} BHD</li>
  </ul>

  <div class="sapce-actions">
    <a class="sapce-btn" href="{% url 'detail' space.id %}">More Details</a>
  </div>
</div>

</div>

<script>
  const toggle = document.querySelector('#dropdown-toggle');
  const menu = document.querySelector('#dropdown-menu');
  const hiddenInput = document.querySelector('#selected-type');

  toggle.addEventListener('click', () => {
    menu.style.display = menu.style.display === 'block' ? 'none' : 'block';
  });

  menu.querySelectorAll('li').forEach(item => {
    item.addEventListener('click', () => {
      toggle.textContent = item.textContent;
      hiddenInput.value = item.dataset.value;
      menu.style.display = 'none';
    });
  });

  document.addEventListener('click', (e) => {
    if (!toggle.contains(e.target) && !menu.contains(e.target)) {
      menu.style.display = 'none';
    }
  });
</script>


{% endfor %}
{% endblock %}

roompickr/main_app/templates/spaces/detail.html
{% extends 'base.html' %}
{% block content %}
<!-- <h1 class="uniq-space-title">Space Details</h1> -->

<div id="imageCarousel" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    {% for image in space.image_set.all %}
      {% load static %}
      <div class="carousel-item {% if forloop.first %}active{% endif %}">
        <img src={% static image.image_space|cut:'main_app/static/' %} class="d-block w-100" alt="this for {{space.name}}">

        <div class="carousel-caption d-none d-md-block">
          <p>{{ image.caption }}</p>
        </div>

        {% if user.is_superuser %}
          <button type="button" class="btn btn-light btn-sm edit-icon" data-bs-toggle="modal" data-bs-target="#editModal{{ image.id }}" style="position: absolute; top: 10px; right: 10px; z-index: 10;">
            ✏️
          </button>

          <div class="modal fade" id="editModal{{ image.id }}" tabindex="-1" aria-labelledby="editModalLabel{{ image.id }}" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="editModalLabel{{ image.id }}">Edit Image</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <form action="{% url 'update_image' space.id image.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="file" name="image_space" accept="image/*" class="form-control mb-2"/>
                    <textarea name="caption" class="form-control mb-2">{{ image.caption }}</textarea>
                    <input type="submit" value="Update" class="btn btn-primary"/>
                  </form>
                  <hr>
                  <form action="{% url 'delete_image' space.id image.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Delete" class="btn btn-danger"/>
                  </form>
                </div>
              </div>
            </div>
          </div>
        {% endif %}

      </div>
    {% endfor %}
  </div>

  <button class="carousel-control-prev" type="button" data-bs-target="#imageCarousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#imageCarousel" data-bs-slide="next">
    <span class="carousel-control-next-icon"></span>
  </button>
</div>

{% if user.is_superuser %}
<button id="openImagePopup" class="popup-btn uniq-add-image-btn">Add a new image</button>
{% endif %}



<div id="imagePopup" class="custom-popup">
  <div class="popup-content">
    <span class="close-btn" id="closeImagePopup">&times;</span>

    {% if user.is_superuser %}
      <form action="{% url 'add_image' space.id %}" method="post" enctype="multipart/form-data" class="custom-image-form uniq-image-form">
        {% csrf_token %}
        {{ image_form.as_p }}
        <input type="submit" value="Add!" />
      </form>
    {% endif %}

  </div>
</div>


<div class="space-details">
  <h1 class="space-title">{{ space.name }}</h1>
  <p class="space-description">{{ space.description }}</p>

<div class="space-stats">
  <div class="stat-grid">
    <div class="stat-item-box full-width">
      <i class="fi fi-ss-map-marker"></i>
      <span>{{ space.address }}</span>
    </div>
    <div class="stat-item-box">
      <i class="fi fi-ss-users"></i>
      <span>Capacity: {{ space.capacity }}</span>
    </div>
    <div class="stat-item-box">
      <i class="fi fi-ss-building"></i>
      <span>Type: {{ space.get_type_display }}</span>
    </div>
    <div class="stat-item-box">
      <i class="fi fi-ss-usd-circle"></i>
      <span>Price/Hour: {{ space.price_per_hour }} BHD</span>
    </div>
  </div>
</div>


  {% if user.is_superuser %}
  <div class="space-actions">
    <a href="{% url 'spaces_update' space.id %}" class="btn-edit">Edit</a>
    <a href="{% url 'spaces_delete' space.id %}" class="btn-delete">Delete</a>
  </div>
  {% endif %}
  <a href="{% url 'start_booking' space.id %}" class="uniq-start-booking-btn">Start Booking</a>
</div>



<div class="uniq-feedback-form">
  <h2 class="feedback-title">Feedback </h2>
  <form action="{% url 'add_feedback' space.id %}" method="post" class="feedback-form">
    {% csrf_token %}
    <textarea name="comment" class="feedback-textarea" placeholder="Write your feedback..."></textarea>
    <button type="submit" class="feedback-btn">Add Feedback</button>
  </form>
</div>

<div class="uniq-feedback-list">
  {% for feedback in space.feedback_set.all %}
    <div class="uniq-feedback-item">
      <span class="feedback-username">{{ feedback.user.profile.full_name }}</span>
      <span class="feedback-date">{{ feedback.created_at }}</span>
      <p class="feedback-comment">{{ feedback.comment }}</p>
      {% if feedback.user == request.user %}
      <form action="{% url 'edit_feedback' space.id feedback.id %}" method="post" class="feedback-edit-form">
        {% csrf_token %}
        <textarea name="comment" class="feedback-textarea-edit">{{ feedback.comment }}</textarea>
        <button type="submit" class="feedback-btn-edit">Update</button>
      </form>
      <form action="{% url 'delete_feedback' space.id feedback.id %}" method="post" class="feedback-delete-form">
        {% csrf_token %}
        <button type="submit" class="feedback-btn-delete">Delete</button>
      </form>
      {% endif %}
    </div>
  {% endfor %}
</div>

<script>
  const openPopupBtn = document.querySelector("#openImagePopup");
  const closePopupBtn = document.querySelector("#closeImagePopup");
  const imagePopup = document.querySelector("#imagePopup");
  const firstItem = document.querySelector('#imageCarousel .carousel-item');

  openPopupBtn.addEventListener("click", () => {
    imagePopup.style.display = "flex";
  });

  closePopupBtn.addEventListener("click", () => {
    imagePopup.style.display = "none";
  });

  document.addEventListener("DOMContentLoaded", () => {
  if(firstItem) {
    firstItem.classList.add('active');
  }
});


</script>

{% endblock %}

roompickr/main_app/templates/spaces/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Space List</h1>
{% for space in spaces %}
  <a href="{% url 'detail' space.id %}">
    <div>
      <div>
        <div>
            <h1>{{ space.name }}</h1>
            <h4>{{ space.capacity }}</h4>
        </div>
      </div>

    </div>
  </a>
{% endfor %}
{% endblock %}

roompickr/main_app/templates/spaces/your_booking.html
{% extends 'base.html' %}
{% block content %}
<div class="booking-history-body">
  <h1 class="booking-history-h1">Your Booking History</h1>
  <div class="booking-history-wrapper">
    {% for book in booking %}
    {% if book.end >= current_time %}
        <section class="booking-history-cards">
          <span class="accent accent-blue" aria-hidden="true"></span>
          <div class="booking-history-cards-content">
            <a href="{% url 'booking_detail' book.id %}" class="booking-history-item">
              <h2 class="booking-history-cards-title">Available | {{ book }}</h2>
            </a>
            <p class="booking-history-cards-subtitle">{{book.end}}</p>
          </div>
        </section>
      {% else %}
      <section class="booking-history-cards-disabled">
          <span class="accent accent-blue" aria-hidden="true"></span>
          <div class="booking-history-cards-content">
              <h2 class="booking-history-cards-title">Expire | {{ book }}</h2>
            <p class="booking-history-cards-subtitle">{{book.end}}</p>
          </div>
        </section>
    {% endif %}
{% endfor %}
</div>
{% endblock %}

roompickr/main_app/templates/spaces/your_space.html
{% extends 'base.html' %}
{% block content %}
<h1 class="spaces-page-title">Space List</h1>
<div class="top-controls">
    <div class="filter-container">
        <form action="{% url 'search_results' %}" method="get" class="filter-form">
          <div class="filter-inline">
            <div class="filter-dropdown">
              <div class="filter-dropdown-toggle" id="dropdown-toggle">Office</div>
              <ul class="filter-dropdown-menu" id="dropdown-menu">
                <li data-value="O">Office</li>
                <li data-value="H">Hall</li>
                <li data-value="M">Meeting Room</li>
              </ul>
            </div>

            <input type="hidden" name="type" id="selected-type" value="O" />
            <button type="submit" class="filter-btn">Filter</button>
          </div>
        </form>
    </div>

    {% if user.is_superuser %}
    <div class="spaces-admin-links">
      <a href="{% url 'spaces_create' %}">Add a Space</a>
    </div>
    {% endif %}
</div>


{% for space in spaces %}
<div class="sapce-card">
    <div class="sapce-card__image">
    {% load static %}
    <img src={% static space.thumbnail|cut:'main_app/static/' %}
  alt="this for {{space.name}}"/>
  </div>

  <div class="sapce-card__content">
  <div class="sapce-title-row">
    <h1 class="sapce-title">{{ space.name }}</h1>
    <span class="sapce-tag">{{ space.get_type_display }}</span>
  </div>

  <ul class="sapce-info">
    <li><i class="fi fi-ss-person-simple space-icon"></i>{{ space.capacity }}</li>
    <li><i class="fi fi-ss-marker space-icon"></i> {{ space.address }}</li>
    <li><i class="fi fi-ss-usd-circle space-icon"></i> {{ space.price_per_hour }} BHD</li>
  </ul>

  <div class="sapce-actions">
    <a class="sapce-btn" href="{% url 'detail' space.id %}">More Details</a>
  </div>
</div>

</div>

<script>
  const toggle = document.querySelector('#dropdown-toggle');
  const menu = document.querySelector('#dropdown-menu');
  const hiddenInput = document.querySelector('#selected-type');

  toggle.addEventListener('click', () => {
    menu.style.display = menu.style.display === 'block' ? 'none' : 'block';
  });

  menu.querySelectorAll('li').forEach(item => {
    item.addEventListener('click', () => {
      toggle.textContent = item.textContent;
      hiddenInput.value = item.dataset.value;
      menu.style.display = 'none';
    });
  });

  document.addEventListener('click', (e) => {
    if (!toggle.contains(e.target) && !menu.contains(e.target)) {
      menu.style.display = 'none';
    }
  });
</script>


{% endfor %}
{% endblock %}